# Generated by Django 2.0.7 on 2018-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20180822_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_of_creations',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
