# Generated by Django 2.0.7 on 2018-08-22 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_auto_20180822_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short_id',
            field=models.SlugField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
